name = "Paradise Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5ee57ec74485b2201fd17ccac7fb1385b6f2f31b33a07edec5d0050811d0787"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
