name = "Paradise Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96fad52d82c91ef462901d7e9845db396b775a08d0988cd7bdbe33619f3251e3"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
