name = "Paradise Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65b6758484c1d6cbab8f431beef003c4c8d5b19cda9587bc00f603fd8c22fc3e"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
