name = "Paradise Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c54712fa59e8f3d22d70bdaacd65857b9044b871ec3e8ca8fcc5400b4a291e12"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
