name = "Paradise Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2908bc47d767c9354b93ef57ac738be5ba59211d84e48703b70a6586f7caf35"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
