name = "Paradise Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbad74fd713bcd095eef2c0b8d4cbe104a8df25f1a06ccc5a16737adb4016b53"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
