name = "Paradise Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eacf52f98b2f21d65b9fc56bf75ea09e3a3e1a87acdddad853f70cf4920fd3b6"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
