name = "Paradise Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30ae39384699817f7f3e420c5a25505a884b863dd7c5824c2bc143e380aac076"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
