name = "Paradise Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fa1f2a65d3c0e56c2445257d59cd93c22c33760aecf839950be2e55a5397777"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
