name = "Paradise Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "354afa9d9933e97f26c7077453067f0e6952a812c13215bfcf015b1f9453f7ac"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
