name = "Paradise Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9202aa2bd295d847eb36606e28b6e92e55a661e4524bbeb339cac465d0284725"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
