name = "Paradise Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb45c20da4223f83aba77e3f36b4259fc63f861080ad8719e22c02b12b97eaee"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
