name = "Paradise Server"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fb016480b526982e6ff9a63138398eb85e07515121a0c269c48eab3ee3cad23"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
